version: "3"

services:
  Notification-postgres:
    image: bitnami/postgresql
    container_name: Notification_Database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mariogomes
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRESQL_DATABASE=notification
    volumes:
      - pgdata:/bitnami/postgresql
    network_mode: host
  app:
    build: .
    container_name: NotificationAPI
    ports:
      - 80:80
    volumes:
      - .:/app
    network_mode: host

volumes:
  pgdata:
    driver: local
